kind: Service
apiVersion: v1
metadata:
  name: pod-az-c
spec:
  type: NodePort
  selector:
    app: pod-az-c
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-az-c
spec:
  selector:
    matchLabels:
      app: pod-az-c
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-az-c
        tier: backend
        track: stable
    spec:
      containers:
        - name: pod-az-c
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: us-west-2c
