apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-ha-host-zone
spec:
  selector:
    matchLabels:
      app: pod-ha-host-zone
  replicas: 3
  template:
    metadata:
      labels:
        app: pod-ha-host-zone
    spec:
      containers:
        - name: pod-ha-host-zone
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - pod-ha-host-zone
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - pod-ha-container
                topologyKey: failure-domain.beta.kubernetes.io/zone
