apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-linux-depl
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beta.kubernetes.io/instance-type
                operator: In
                values:
                  - r5.8xlarge
                  - c5.9xlarge
                  - m5.8xlarge
  containers:
    - name: nodeselector-linux
      image: "gcr.io/google-samples/hello-go-gke:1.0"
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
