apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-toleration-depl
spec:
  selector:
    matchLabels:
      app: pod-toleration
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-toleration
        tier: backend
        track: stable
    spec:
      containers:
        - name: pod-toleration
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      tolerations:
        - key: "node"
          operator: "Equal"
          value: "taint"
          effect: "NoSchedule"
      nodeSelector:
        node: taint
