apiVersion: v1
kind: Pod
metadata:
  name: pod-antiaffinity-not-core
  labels:
    service: not-core
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: service
                operator: In
                values:
                  - core
          topologyKey: kubernetes.io/hostname
  containers:
    - name: nodeselector-linux
      image: "gcr.io/google-samples/hello-go-gke:1.0"
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
