apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-core-a
  labels:
    service: core
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: service
                operator: In
                values:
                  - core
          topologyKey: kubernetes.io/hostname
  containers:
    - name: nodeselector-linux
      image: "gcr.io/google-samples/hello-go-gke:1.0"
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-core-b
  labels:
    service: core
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: service
                operator: In
                values:
                  - core
          topologyKey: failure-domain.beta.kubernetes.io/host
  containers:
    - name: nodeselector-linux
      image: "gcr.io/google-samples/hello-go-gke:1.0"
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
